name: ml_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - scikit-learn
  - pandas
  - joblib
  - jupyter
  - ipykernel
  - numpy
  - scipy
  - pip:
    - datasets
    - transformers
    - torch
    - tqdm
    - huggingface-hub
    - sacred
    - mlflow
    - matplotlib
    - seaborn
    - protobuf
    - cloudpickle
    - packaging
    - psutil
    - requests
    - pyyaml
    - gitpython
    - alembic
    - sqlalchemy
    - click
    - python-dateutil
    - boto3
    - scikit-learn-intelex
    - ipywidgets
    - notebook
    - jupyterlab
    - nbformat
    - nbconvert
    - widgetsnbextension
    - nltk
    - regex
    - filelock
    - typing-extensions
    - fsspec
    - aiohttp
    - aiosignal
    - async-timeout
    - attrs
    - certifi
    - charset-normalizer
    - frozenlist
    - idna
    - multidict
    - yarl 